[build]
  base = "frontend"
  command = "rm -rf ../node_modules node_modules package-lock.json && cd .. && npm install && cd frontend && npm install @rollup/rollup-linux-x64-gnu --save-optional && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
